const animeList = [
    "Dragon ball",
    "Bleach",
    "Naruto",
    "Sakura no Onozuka",
    "Kono Subarashii Sekai ni Shukufuku wo! ",
    "Sword Art Online",
    "Bakuman",
    "Dororo",
    "Black clover",
    "Steins;Gate",
    "Solo leveling",
    "Re:Zero",
    "K-On!",
    "Akira",
    "Berserk",
    "Suzume no Tojimari",
    "Kaguya-sama: Love Is War",
    "Yu-Gi-Oh",
    "Saint Seiya",
    "Kimetsu No Yaiba : Demon Slayer",
    "Kusuriya no Hitorigoto : The Apothecary Diaries",
    "Parasyte",
    "Dr.Stone",
    "Sousou no Frieren",
    "Death Note",
    "Monster",
    "Jujutsu Kaisen",
    "One Piece",
    "Shingeki no Kyojin : Attack on titan",
    "Chainsaw man",
    "Dandadan",
    "One Punch Man",
    "Blue lock",
    "Devilman: Crybaby",
    "Tokyo ghoul",
    "Tokyo revengers",
    "Captain Tsubasa",
    "Fullmetal Alchemist: Brotherhood",
    "My hero academia : Boku no Hero Academia",
    "Hunter x hunter",
    "Code Geass",
    "Kuroko no Basket",
    "Haikyuu!!",
    "Sakura-sama: The Animation",
    "Kuroko no Basuke",
    "Kamisama no Nagasaki",
    "Akame ga Kill",
    "Fairy Tails",
    "Seven deadly Sins",
    "Violet Evergarden",
    "Your Name"

]

export default animeList