const animeList = [
    "Dragon ball",
    "Bleach",
    "Dororo",
    "Black clover",
    "Naruto",
    "Steins;Gate",
    "Solo leveling",
    "Re:Zero",
    "Yu-Gi-Oh",
    "Saint Seiya",
    "Kimetsu No Yaiba : Demon Slayer",
    "Kusuriya no Hitorigoto : The Apothecary Diaries",
    "Parasyte",
    "Dr.Stone",
    "Sousou no Frieren",
    "Death Note",
    "Monster",
    "Jujutsu Kaisen",
    "One Piece",
    "Shingeki no Kyojin : Attack on titan",
    "Chainsaw man",
    "Dandadan",
    "One Punch Man",
    "Blue lock",
    "Devilman: Crybaby",
    "Tokyo ghoul",
    "Tokyo revengers",
    "Captain Tsubasa",
    "Fullmetal Alchemist: Brotherhood",
    "My hero academia",
    "Hunter x hunter",
    "Code Geass",
    "Kuroko no Basket",
    "Haikyuu!!"
]

export default animeList